version: "3.3"
name: "node-sequelize"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: node-sequelize
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    tmpfs:
      - /var/lib/postgresql/data
      - /tmp
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    tmpfs:
      - /data
